[project]
authors = ["Alex Crosby <crosbyar@gmail.com>"]
channels = ["conda-forge"]
description = "A Python package for creating, deploying and modifying Nebula mesh networks using Pydantic models."
name = "maloja"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
# serve-docs = "python -m pdoc -d google --mermaid ../maloja !maloja.test_nebula !pydantic"
serve-docs = "python -m pdoc -d google --mermaid ../maloja !maloja.test_nebula"
export-docs = "python -m pdoc -d google --mermaid -o docs/ ../maloja !maloja.test_nebula"

[dependencies]
python = ">=3.10,<3.11"
gcc = ">=15.1.0,<16"
pygraphviz = ">=1.14,<2"
pdoc = ">=14.4.0,<15"

[pypi-dependencies]
typer = "*"
pydantic = "*"
pydantic-settings = "*"
numpy = ">=2.2.5, <3"
erdantic = ">=1.1.0.post1, <2"
autodoc-pydantic = "*"
datamodel-code-generator = ">=0.31.2, <0.32"
docker = ">=7.1.0, <8"
